spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0

logging:
  pattern:
    level: "%5p [ ${spring.application.name:} trace_id=%X{traceId:-} span_id=%X{spanId:-} ]"

#logging.config: classpath:logback/logback-${spring.profiles.active}.xml