spring:
  sleuth:
    sampler:
      probability: 1
  application:
    name: client
  profiles:
    active: local

  config:
    import:
      - logging.yaml
#      - db-main.yml
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local


---

spring:
  config:
    activate:
      on-profile: prod